package server;

import java.io.Serializable;

/**
 * This class provides an abstract exception that can be generated by any
 * magic server. This can be used to "wrap" other exceptions generated
 * by server implementations.
 * @author Kevin Filanowski
 * @author Donny Queen
 * @version October 2018
 */
public class MagicServerException extends Exception implements Serializable {
	/**
	 * Creates a new MagicServerException with no message.
	 */
	public MagicServerException() {
		super();
	}

	/**
	 * Creates a new MagicServerException with the specified message.
	 * @param message The specified message.
	 */
	public MagicServerException(String message) {
		super(message);
	}

	/**
	 * Creates a new MagicServerException with the specified message,
	 * and wraps the specified Throwable object.
	 * @param message The specified message.
	 * @param throwable The specified Throwable object.
	 */
	public MagicServerException(String message, Throwable throwable) {
		super(message, throwable);
	}

	/**
	 * Creates a new MagicServerException that wraps the 
	 * specified Throwable object.
	 * @param throwable The specified Throwable object.
	 */
	public MagicServerException(Throwable throwable) {
		super(throwable);
	}
}
